#!/bin/bash


# ./fingerprint.sh "PorcoRosso.mp4" "Porco\nRosso"
# ./fingerprint.sh "Ponyo.mp4" "Ponyo"
# ./fingerprint.sh "WindRises.mp4" "The Wind\nRises"
# ./fingerprint.sh "Totoro.mp4" "My\nNeighbor\nTotoro"
# ./fingerprint.sh "Nausicaa.mp4" "Nausica0xC3\nof the\nValley\nof the\nWind"
# ./fingerprint.sh "PrincessMononoke.mp4" "Princess\nMononoke"
# ./fingerprint.sh "SpiritedAway.mp4" "Spirited\nAway"
# ./fingerprint.sh "KikisDeliveryService.mp4" "Kiki's\nDelivery\nService"
# ./fingerprint.sh "HowlsMovingCastle.m4v" "Howl's\nMoving\nCastle"
# ./fingerprint.sh "CastleInTheSky.mp4" "Castle\nIn The\nSky"

# ./fingerprint.sh "WALL-E.mp4" "WALL-E"
# ./fingerprint.sh "Snowpiercer.mp4" "Snowpiercer"
# ./fingerprint.sh "Soul.mp4" "Soul"
# ./fingerprint.sh "Interstellar.mp4" "Interstellar"
# ./fingerprint.sh "Gattaca.mp4" "Gattaca"
# ./fingerprint.sh "Gravity.mp4" "Gravity"

# ./fingerprint.sh "STIntoDarkness.mp4" "Star Trek\nInto\nDarkness"
# ./fingerprint.sh "LovingVincent.mp4" "Loving\nVincent"
# ./fingerprint.sh "TheMartian.mp4" "The\nMartian"
# ./fingerprint.sh "TwelveMonkeys.mp4" "Twelve\nMonkeys"
./fingerprint.sh "Moon.mp4" "Moon"
# ./fingerprint.sh "GrandBudapest.mp4" "The Grand\nBudapest\nHotel"
# ./fingerprint.sh "EternalSunshine.mp4" "Eternal\nSunshine\nof the\nSpotless\nMind"
# ./fingerprint.sh "Jojo.mp4" "Jojo Rabbit"
# ./fingerprint.sh "Amelie.mp4" "Amélie"

# ./fingerprint.sh "Solaris.mp4" "Solaris"
# ./fingerprint.sh "STBeyond.mp4" "Star Trek:\nBeyond"
# ./fingerprint.sh "StarTrek.mp4" "Star Trek"
# ./fingerprint.sh "Arrival.mp4" "Arrival"
# ./fingerprint.sh "JoJo.mp4" "Jojo\nRabbit"
# ./fingerprint.sh "Rogue.mp4" "Rogue\nOne"
# ./fingerprint.sh "Clockwork.mp4" "A\nClockwork\nOrange"
# ./fingerprint.sh "2001.mp4" "2001\nA Space\nOdyssey"
# ./fingerprint.sh "ModernTimes.mp4" "Modern\nTimes"
# ./fingerprint.sh "Monsters.mp4" "Monsters\nInc."
# ./fingerprint.sh "Coco.mp4" "Coco"